- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/__init__.py
- mindsdb_sql_parser/parser.py
Changes:
- Added Id keywords from which worked in mysql dialect
- added 'dialect' argument to parser_sql for back compatibility
> Added Id keywords from which worked in mysql dialect

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_structure.py
Example:
```sql
select * from table1 a
inner join table2 b on a.x = b.y  and k = p,
table3,
table4
```
Also updated version to '0.1.0'
> Mixed join support

- mindsdb_sql_parser/ast/select/operation.py
If is required by sqlalchemy render tests, used by this PR: https://github.com/mindsdb/mindsdb/pull/10310
> Window function: add frame options to to_tree

- mindsdb_sql_parser/lexer.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_structure.py
ASOF join example:
```
SELECT *
FROM table_1
ASOF JOIN table_2 ON (symbol)
```
Used in:
- [snowflake](https://docs.snowflake.com/en/sql-reference/constructs/asof-join)
- [duckdb](https://duckdb.org/docs/guides/sql_features/asof_join.html)
- [questdb](https://questdb.com/docs/reference/sql/asof-join/)
- [clickhouse](https://clickhouse.com/docs/ru/sql-reference/statements/select/join)
- and others
Required by https://linear.app/mindsdb/issue/BE-608/asof-join-support
> Asof join support

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/ast/select/identifier.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_structure.py
- tests/test_standard_render.py
Memorize the qouted parts of Identifier in .is_quoted attrubute
> Memorize the qouted parts of Identifier

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_structure.py
For the case 
```
`a`.*
```
`is_quoted` used to be [True]. The correct is [True, False]
> Fix is quoted

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/lexer.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_structure.py
Example query:
```sql
SELECT t.name AS name, t.driver AS driver, r.*
FROM tags t INNER JOIN LATERAL
(SELECT longitude, latitude
FROM readings r
WHERE r.tags_id=t.id
ORDER BY time DESC LIMIT 1)  r ON true
WHERE t.name IS NOT NULL
AND t.fleet = 'South'
```
> Support lateral join

- mindsdb_sql_parser/ast/select/select.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_structure.py
Example query: 
```sql
SELECT DISTINCT ON (t.hostname) * FROM tags t 
```
> Support `distinct on`

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/ast/create.py
- mindsdb_sql_parser/ast/select/identifier.py
- mindsdb_sql_parser/lexer.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_create.py
- tests/test_mindsdb/test_oracle.py
Added support:
- marker of outer join in implicit join
```sql
SELECT *
FROM A, B
WHERE A.column(+) = B.column
```
- Oracle limit
```sql
SELECT * FROM products
FETCH NEXT 2 ROWS ONLY
```
- Precision in column type
```sql
create table store
(
id integer  not null,
balance decimal(5,2)  <--  
);
```
> Update for oracle TPC DS/H benchmarks

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/ast/variable.py
- mindsdb_sql_parser/lexer.py
- mindsdb_sql_parser/parser.py
- tests/test_mindsdb/test_knowledgebase.py
It can be used for knowledge bases:
```sql
CREATE KNOWLEDGE_BASE test_kb
USING
embedding_model = {
"provider": "openai",
"model_name" : "text-embedding-3-large",
"api_key": @api_key1   --  <--
}
```
> Json can have variable in value

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/lexer.py
- tests/test_mindsdb/test_variables.py
Fix parsing error when system variable has two parts:
```sql
select @@session.auto_increment_increment
```
> Fixed system variable parsing

- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_create.py
Support length in primary key type 
```sql
CREATE TABLE  local_pg.use_cases (
name                VARCHAR(255) PRIMARY KEY NOT NULL,  -- <--
description         TEXT,
);
```
> Support length in primary key type 

- mindsdb_sql_parser/ast/mindsdb/__init__.py
- mindsdb_sql_parser/ast/mindsdb/alter_database.py
- mindsdb_sql_parser/parser.py
- tests/test_mindsdb/test_databases.py
This PR adds the syntax for `ALTER DATABASE`.
Fixes https://linear.app/mindsdb/issue/BE-1018/add-update-database-syntax-to-the-parser
> Added the Syntax for ALTER DATABASE

- mindsdb_sql_parser/ast/mindsdb/__init__.py
- mindsdb_sql_parser/ast/mindsdb/alter_view.py
- mindsdb_sql_parser/parser.py
- tests/test_mindsdb/test_views.py
This PR adds the syntax for `ALTER VIEW`.
Fixes https://linear.app/mindsdb/issue/BE-1020/add-alter-view-syntax-to-the-parser
> Added the Syntax for ALTER VIEW

- mindsdb_sql_parser/ast/select/union.py
- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_union.py
Enhanced the SQL parser to support the DISTINCT keyword with set operations (UNION, INTERSECT, and EXCEPT).
Example:
```sql
table a INTERSECT DISTINCT table b;
```
> `DISTINCT` keyword for `UNION/INTERSECT/EXCEPT`

- mindsdb_sql_parser/ast/select/identifier.py
- tests/test_base_sql/test_ast.py
Fix issue with copy identifier.is_quoted:
```
deepcopy(Identifier('`a`')).is_quoted == [False]
```
> Fix identifier copy and deepcopy

- mindsdb_sql_parser/ast/select/operation.py
- tests/test_base_sql/test_select_structure.py
Before the fix this query 
```sql
select * from test_kb_crm where id in (1000)
```
is parsed the same as 
```sql
select * from test_kb_crm where id in 1000
```
The update: 
If element of operation has parentheses=False - wrap it to Tuple
Fixes https://linear.app/mindsdb/issue/UNI-149/query-id-=-555-and-id-in-555
> Fix query with single value in IN

- mindsdb_sql_parser/parser.py
- tests/test_mindsdb/test_agents.py
Support ALTER AGENT syntax
```sql
ALTER AGENT my_agent
USING
model = 'gemini-2.0-flash',
api_key = 'xyz123', 
```
is alias to:
```sql
UPDATE AGENT my_agent
SET
model = 'gemini-2.0-flash',
api_key = 'xyz123', 
```
Fixes: https://linear.app/mindsdb/issue/RES-34/syntax-for-update-agent
> Alter Agent syntax

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/ast/select/operation.py
- mindsdb_sql_parser/parser.py
Fix for the query:
```sql
select * from int2.tab1
where x1 in (select id from int1.tab1)
```
The condition is made as: `BinaryOperation(Identifier('x1'), Tuple(Select(...)))`
> Fix IN with SELECT: move 'in' logic outside of Operation class

- mindsdb_sql_parser/__about__.py
- sly/lex.py
If the query contains a large string, the memory consumption during parsing could also be large.
This PR split original `lex` regexp into to: with and without 'find string' parts. These regular expressions are applied in sequence, allowing for x10 reduction in memory consumption.
For 2x100kb strings:
- memory consumption reduced `1116` -> `90` Mb
- processing time reduced  by about x10
> Workaround for big strings parsing

- mindsdb_sql_parser/lexer.py
- mindsdb_sql_parser/parser.py
- tests/test_mindsdb/test_selects.py
> Fix raw query escaping

- mindsdb_sql_parser/parser.py
- tests/test_base_sql/test_select_common_table_expression.py
Fix for queries with multiple CTE and UNION in it, like this one:
```sql
WITH ta AS (
SELECT 'a' AS a
UNION
SELECT 'b' AS a
), tb AS (
SELECT 'c' AS a
UNION
SELECT 'd' AS a
)
SELECT a FROM ta
UNION
SELECT a FROM tb
```
> Fix CTE with UNION

- mindsdb_sql_parser/__about__.py
- mindsdb_sql_parser/lexer.py
- mindsdb_sql_parser/parser.py
- tests/test_mindsdb/test_selects.py
Added support of array operators:
- `@>` contains
- `<@` is contained by
- `&&` overlap
https://postgrespro.ru/docs/postgrespro/9.5/functions-array
Fixes https://linear.app/mindsdb/issue/CONN-1415/sema4-support-in-parser
> Array operators supports

- mindsdb_sql_parser/ast/create.py
- requirements_test.txt
- tests/test_base_sql/test_create.py
If CreateTable contains columns with sqlalchemy types, then it may fail when dump to string.
```sql
from sqlalchemy.types import Date
from mindsdb_sql_parser.ast import *
ast = CreateTable(name='test', columns=[TableColumn(name='test', type=Date)], is_replace=True)
ast.to_string()
```
> Fix `CreateTable` dump to string
